[project]
name = "geoplotlib"
version = "0.1.0"
description = "plot geophysical maps"
readme = "README.md"
authors = [
    { name = "Sonder Merak", email = "merak19981999@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "pygmt>=0.17.0",
    "scipy>=1.16.3",
    "tqdm>=4.67.1",
    "xarray>=2025.11.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
